import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  APP_VERSION,
  ROLES,
  ROLE_LEVEL,
  DEFAULT_PERMISSIONS,
  Role,
} from '../../../packages/shared/src';
import './styles.css';
const nav=['Overview','Organizations','Users & Roles','Licenses','Subscriptions','Payments','Automations','AI Config','Integrations','Devices','Updates','Audit Logs','System'];
function App(){const [tab,setTab]=useState('Overview'); const [org,setOrg]=useState('Summit Dental'); const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [role,setRole]=useState<Role>('ADMIN'); const [msg,setMsg]=useState('');
const create=async()=>{if(!email||!name)return setMsg('Name and email are required.'); setMsg('User provisioning request ready. Connect API endpoint to create the Supabase Auth user securely.');};
return <div className="shell"><aside><div className="brand">DentaGrow <span>SUPER ADMIN</span></div>{nav.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<div className="ver">v{APP_VERSION}<br/>Stable release channel</div></aside><main><header><div><small>GLOBAL CONTROL CENTER</small><h1>{tab}</h1></div><div className="pill">SUPER_ADMIN</div></header>{tab==='Overview'&&<><section className="grid"><Card t="Organizations" v="1" s="Active clinic tenants"/><Card t="Users" v="—" s="Live Supabase count"/><Card t="Licenses" v="—" s="Server-connected"/><Card t="System" v="Healthy" s="Architecture checkpoint"/></section><Panel title="Architecture"><p>Centralized multi-tenant control plane. Super Admin can manage clinics, users, licenses, subscriptions, automations, integrations, devices, releases and audit logs.</p></Panel></>}{tab==='Users & Roles'&&<><Panel title="Create child user"><p>Super Admin can create users in any organization. Auth user creation must happen through the secure API, never from the browser with a service-role key.</p><div className="form"><input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Organization" value={org} onChange={e=>setOrg(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as Role)}>{ROLES.map(r=><option key={r} value={r}>{r}</option>)}</select><button className="primary" onClick={create}>Create Child User</button></div><p className="muted">Selected role level: {ROLE_LEVEL[role]}. Default permissions: {DEFAULT_PERMISSIONS[role].length}.</p>{msg&&<div className="notice">{msg}</div>}</Panel></>}{tab==='Organizations'&&<Panel title="Organizations"><Row a="Summit Dental" b="PRO • Active"/><Row a="Create organization" b="API required"/></Panel>}{tab==='Updates'&&<Panel title="Software Updates"><Row a={'Current version '+APP_VERSION} b="Stable"/><Row a="Release validation" b="Checksum + signature required"/><Row a="Rollback" b="Supported by release channels"/></Panel>}{!['Overview','Users & Roles','Organizations','Updates'].includes(tab)&&<Panel title={tab}><p>This control module is scaffolded and wired for the same centralized architecture. Connect its API resource without exposing secrets to the client.</p></Panel>}</main></div>}
const Card=({t,v,s}:{t:string,v:string,s:string})=><div className="card"><small>{t}</small><strong>{v}</strong><span>{s}</span></div>; const Panel=({title,children}:{title:string,children:React.ReactNode})=><section className="panel"><h2>{title}</h2>{children}</section>; const Row=({a,b}:{a:string,b:string})=><div className="row"><span>{a}</span><span>{b}</span></div>; createRoot(document.getElementById('root')!).render(<App/>);
